# Generated by Django 4.2.7 on 2025-12-29 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.CharField(max_length=100, verbose_name='Kategori Adı (TR)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Kategori Adı (EN)')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Blog Kategorisi',
                'verbose_name_plural': 'Blog Kategorileri',
                'ordering': ['name_tr'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(max_length=200, verbose_name='Başlık (TR)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Başlık (EN)')),
                ('content_tr', models.TextField(verbose_name='İçerik (TR)')),
                ('content_en', models.TextField(blank=True, verbose_name='İçerik (EN)')),
                ('cover_image', models.ImageField(upload_to='blog/', validators=[utils.validators.validate_image_size, utils.validators.validate_image_type], verbose_name='Kapak Resmi')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='URL')),
                ('meta_description_tr', models.CharField(blank=True, help_text='SEO için kısa açıklama (maks. 160 karakter)', max_length=160, verbose_name='Meta Açıklama (TR)')),
                ('meta_description_en', models.CharField(blank=True, max_length=160, verbose_name='Meta Açıklama (EN)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Yayında')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Yayın Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-publish_date', '-created_at'],
                'indexes': [models.Index(fields=['is_published', '-publish_date'], name='blog_blogpo_is_publ_4c9e45_idx'), models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx')],
            },
        ),
    ]
