# Generated by Django 4.2.7 on 2025-12-29 21:09

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(max_length=200, verbose_name='Başlık (TR)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Başlık (EN)')),
                ('description_tr', models.TextField(verbose_name='Açıklama (TR)')),
                ('description_en', models.TextField(blank=True, verbose_name='Açıklama (EN)')),
                ('cover_image', models.ImageField(upload_to='services/covers/', validators=[utils.validators.validate_image_size, utils.validators.validate_image_type], verbose_name='Kapak Resmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', validators=[utils.validators.validate_image_size, utils.validators.validate_image_type], verbose_name='Resim')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='Hizmet')),
            ],
            options={
                'verbose_name': 'Hizmet Resmi',
                'verbose_name_plural': 'Hizmet Resimleri',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'order'], name='services_se_is_acti_dbc8d8_idx'),
        ),
    ]
