# Generated by Django 4.2.7 on 2025-12-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_tr', models.TextField(verbose_name='Adres (TR)')),
                ('address_en', models.TextField(blank=True, verbose_name='Adres (EN)')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('working_hours_weekday_tr', models.CharField(help_text='Örn: Pazartesi-Cuma 09:00-18:00', max_length=200, verbose_name='Hafta İçi Çalışma Saatleri (TR)')),
                ('working_hours_weekday_en', models.CharField(blank=True, max_length=200, verbose_name='Hafta İçi Çalışma Saatleri (EN)')),
                ('working_hours_weekend_tr', models.CharField(help_text='Örn: Cumartesi-Pazar 10:00-16:00', max_length=200, verbose_name='Hafta Sonu Çalışma Saatleri (TR)')),
                ('working_hours_weekend_en', models.CharField(blank=True, max_length=200, verbose_name='Hafta Sonu Çalışma Saatleri (EN)')),
                ('google_maps_embed_url', models.URLField(blank=True, help_text="Google Maps'ten iframe embed URL'sini yapıştırın", verbose_name='Google Maps Embed URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('admin_email', models.EmailField(help_text='İletişim formu ve bildirimler için e-posta adresi', max_length=254, verbose_name='Admin E-posta')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
