# Generated by Django 4.2.7 on 2025-12-29 21:09

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_photo', models.ImageField(upload_to='testimonials/', validators=[utils.validators.validate_image_size, utils.validators.validate_image_type], verbose_name='Evcil Hayvan Fotoğrafı')),
                ('owner_name', models.CharField(blank=True, max_length=200, verbose_name='Sahip Adı')),
                ('pet_name', models.CharField(blank=True, max_length=200, verbose_name='Evcil Hayvan Adı')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Açıklama')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Onaylandı')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
            ],
            options={
                'verbose_name': 'Fotoğraf Paylaşımı',
                'verbose_name_plural': 'Fotoğraf Paylaşımları',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['is_approved', '-submitted_at'], name='testimonial_is_appr_c2b9c2_idx')],
            },
        ),
    ]
