# Generated by Django 4.2.7 on 2025-12-29 21:09

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('title_tr', models.CharField(max_length=200, verbose_name='Ünvan (TR)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Ünvan (EN)')),
                ('specialty_tr', models.CharField(max_length=200, verbose_name='Uzmanlık (TR)')),
                ('specialty_en', models.CharField(blank=True, max_length=200, verbose_name='Uzmanlık (EN)')),
                ('bio_tr', models.TextField(verbose_name='Biyografi (TR)')),
                ('bio_en', models.TextField(blank=True, verbose_name='Biyografi (EN)')),
                ('photo', models.ImageField(upload_to='team/', validators=[utils.validators.validate_image_size, utils.validators.validate_image_type], verbose_name='Fotoğraf')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Ekip Üyesi',
                'verbose_name_plural': 'Ekip Üyeleri',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='team_teamme_is_acti_2b6e1b_idx')],
            },
        ),
    ]
