# Generated by Django 5.2.7 on 2026-01-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='specialty_tr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Uzmanlık (TR)'),
        ),
    ]
