# Generated by Django 4.2.7 on 2025-12-29 21:09

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(max_length=200, verbose_name='Başlık (TR)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Başlık (EN)')),
                ('image', models.ImageField(upload_to='clinic/', validators=[utils.validators.validate_image_size, utils.validators.validate_image_type], verbose_name='Resim')),
                ('category_tr', models.CharField(help_text='Örn: Muayene Odası, Cerrahi, Bekleme Alanı', max_length=100, verbose_name='Kategori (TR)')),
                ('category_en', models.CharField(blank=True, max_length=100, verbose_name='Kategori (EN)')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Klinik Resmi',
                'verbose_name_plural': 'Klinik Galerisi',
                'ordering': ['order', 'category_tr'],
                'indexes': [models.Index(fields=['category_tr', 'order'], name='gallery_cli_categor_c6200b_idx')],
            },
        ),
    ]
