# Generated by Django 4.2.7 on 2025-12-30 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_url', models.URLField(blank=True, null=True)),
                ('profile_photo_url', models.URLField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
                ('relative_time_description', models.CharField(max_length=100)),
                ('language', models.CharField(default='tr', max_length=10)),
                ('review_id', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Google Review',
                'verbose_name_plural': 'Google Reviews',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='ReviewsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=200, unique=True)),
                ('last_fetched', models.DateTimeField(default=django.utils.timezone.now)),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('total_reviews', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Reviews Cache',
                'verbose_name_plural': 'Reviews Cache',
            },
        ),
    ]
